Console.WriteLine("Escreva algo em leet!");

string palavraNormal = Console.ReadLine()!;

string palavraLeet = palavraNormal


.Replace("a", "4")
.Replace("á", "4")
.Replace("â", "4")
.Replace("ã", "4")
.Replace("b", "8")
.Replace("c", "[")
.Replace("d", "|))")
.Replace("e", "3")
.Replace("é", "3")
.Replace("ê", "3")
.Replace("f", "|=")
.Replace("g", "6")
.Replace("h", "#")
.Replace("i", "!")
.Replace("í", "!")
.Replace("j", ";")
.Replace("k", "|<")
.Replace("l", "1")
.Replace("m", "//.")
.Replace("n", "//")
.Replace("o", "0")
.Replace("ó", "0")
.Replace("ô", "0")
.Replace("õ", "0")
.Replace("p", "|^")
.Replace("q", "9")
.Replace("r", "|2")
.Replace("s", "5")
.Replace("t", "+")
.Replace("u", "(_)")
.Replace("ú", "(_)")
.Replace("û", "(_)")
.Replace("v", "\\/")
.Replace("w", "\\/\\/")
.Replace("x", " ><")
.Replace("y", "`/")
.Replace("z", "2")


.Replace("A", "4")
.Replace("Á", "4")
.Replace("Â", "4")
.Replace("Ã", "4")
.Replace("B", "8")
.Replace("C", "[")
.Replace("D", "|))")
.Replace("E", "3")
.Replace("É", "3")
.Replace("Ê", "3")
.Replace("F", "|=")
.Replace("G", "6")
.Replace("H", "#")
.Replace("I", "!")
.Replace("Í", "!")
.Replace("J", ";")
.Replace("K", "|<")
.Replace("L", "1")
.Replace("M", "//.")
.Replace("N", "//")
.Replace("O", "0")
.Replace("Ó", "0")
.Replace("Ô", "0")
.Replace("Õ", "0")
.Replace("P", "|^")
.Replace("Q", "9")
.Replace("R", "|2")
.Replace("S", "5")
.Replace("T", "+")
.Replace("Ú", "(_)")
.Replace("Ú", "(_)")
.Replace("Û", "(_)")
.Replace("V", "\\/")
.Replace("W", "\\/\\/")
.Replace("X", " ><")
.Replace("Y", "`/")
.Replace("Z", "2");


Console.WriteLine($"Isso em leet é: {palavraLeet}");
